### ISSUE TITLE
Issues accessing data

### ISSUE THREAD

**Issue by tjiagoM** [welch-lab/SquiggleNet#1]
Hi!

I was trying to reproduce your paper using the shared data. I think I was able to download the data using the sra toolkit provided by NCBI, but the data comes in the .fastq format rather than the .fast5 you use in the paper. I was not able to find a converter but I feel something is wrong because you don't mention any .fastq format in the paper. These are the two datasets I downloaded: https://www.ncbi.nlm.nih.gov/sra/?term=SRP296988

Would you be able to help me understand whether I'm looking to the wrong places and how to access the .fast5 files you used?

Thanks!

**Comment by Anbyew** [comment]
Hello! Thanks for your interests in our work. The fast5 datasets are available on demand due to the size of the files. Please send your request to yuweibao@umich.edu. We are happy to work with you on transferring the large datasets.
