### ISSUE TITLE
Read until Integration?

### ISSUE THREAD

**Issue by carze** [welch-lab/SquiggleNet#4]
Hi,

Awesome work on the paper and development of this tool. I might be missing something but is SquiggleNet not directly implementing the ONT read until functionality to execute during a live Nanopore run? If not, is their any intention to add this functionality or is it best left to each user to integrate in themselves?

Thanks!

**Comment by Anbyew** [comment]
Hello! Thanks for your interests in SquiggleNet. The ONT Read Until API can be found [here](https://github.com/nanoporetech/read_until_api). It is left for the user to integrate flexibly according to their sequencing environment.
