### ISSUE TITLE
Inquiry about the CKPT files in models directory

### ISSUE THREAD

**Issue by khyox** [welch-lab/SquiggleNet#7]
The CKPT files in the repo's `models` directory seem to contain the model "state dictionary" (typically with PTH extension instead) for a pre-trained ResNet_1000 model, with BottleNeck block, and layers [2,2,2,2], possibly using the Adam optimizer, and perhaps trained using 3000 signals per read. Can you please confirm? Also, which are the differences between them? Is one of them pre-trained using the HeLa&Zymo dataset and the other on the Human&Zymo_b12 dataset? Many thanks!

**Comment by Anbyew** [comment]
Yes and Yes! [model_B4_2_3000_totmad_br_2.ckpt](https://github.com/welch-lab/SquiggleNet/blob/master/models/model_B4_2_3000_totmad_br_2.ckpt) was trained on the Human&Zymo_b12 dataset, and [model_B4t2_3000_tot32.ckpt](https://github.com/welch-lab/SquiggleNet/blob/master/models/model_B4t2_3000_tot32.ckpt) was trained on the HeLa&Zymo dataset.

**Comment by khyox** [comment]
Many thanks for the confirmation!
